name: apoiosisgpenv
channels:
  - defaults
dependencies:
  - altgraph=0.17=pyhd3eb1b0_0
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py39haa95532_0
  - click=8.0.1=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - future=0.18.2=py39haa95532_1
  - importlib-metadata=3.10.0=py39haa95532_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.0.1=pyhd3eb1b0_0
  - macholib=1.14=pyhd3eb1b0_1
  - markupsafe=2.0.1=py39h2bbff1b_0
  - openssl=1.1.1l=h2bbff1b_0
  - pefile=2019.4.18=py_0
  - pip=21.2.4=py38haa95532_0
  - pycryptodome=3.10.1=py39h2bbff1b_0
  - pyinstaller=3.6=py39h8cc25b3_6
  - python=3.9.6=h6244533_1
  - pywin32=228=py39hbaba5e8_1
  - pywin32-ctypes=0.2.0=py39haa95532_1000
  - setuptools=52.0.0=py39haa95532_0
  - tzdata=2021a=h5d7bf9c_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - wincertstore=0.2=py39h2bbff1b_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - pip:
    - alembic==1.7.1
    - blinker==1.4
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - colorama==0.4.4
    - dnspython==2.1.0
    - email-validator==1.1.3
    - flask-login==0.5.0
    - flask-mail==0.9.1
    - flask-migrate==3.1.0
    - flask-sqlalchemy==2.5.1
    - flask-wtf==0.15.1
    - greenlet==1.1.1
    - httplib2==0.19.1
    - idna==3.2
    - mako==1.1.5
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - requests==2.26.0
    - rsa==4.7.2
    - six==1.16.0
    - sqlalchemy==1.4.23
    - uritemplate==3.0.1
    - urllib3==1.26.6
    - wtforms==2.3.3
prefix: C:\Users\cimeibt\Anaconda3\envs\apoiosisgp
